[project]
name = "pythonminecraftlauncher"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "aiofiles>=24.1.0",
    "aiohttp>=3.12.15",
    "keyring>=25.6.0",
    "msal>=1.34.0",
    "pyperclip>=1.11.0",
]
